### PR TITLE
Add german locale

### PR DESCRIPTION
**Pull request by Y0ngg4n**

### CODE REVIEW

**Comment by JarbasAl** [comment]
thank you! note that this skill depends on https://github.com/OpenVoiceOS/skill-ovos-common-play that also needs translation

**Comment by Y0ngg4n** [comment]
@JarbasAl  why dont you use default playback system?

**Comment by JarbasAl** [comment]
essentially because it doesnt support video, i implemented my own playback stack which includes the whole UI, playlists handling, displaying search results etc. This isnt possible in regular mycroft-core

They seem to be finally getting to it, but my version has existed in some form or another for around 1 year now so i'm not throwing it away :man_shrugging: 

also note i tried to upstream this before rolling my own and the mycroft team is aware of it

**Comment by Y0ngg4n** [comment]
@JarbasAI ah ok thank you

**Comment by JarbasAl** [comment]
maybe i will write a blog post introducing the stack once ovos-common-play goes into beta (currently alpha, still missing features like shuffle/repeat etc)

the main conflict is the official skill capturing the "play XXX" queries, so it needs to be blacklisted for now, old skills (mycroft style) should still work, but compatibility its a bit wonky and needs some love.

**Comment by Y0ngg4n** [comment]
@JarbasAI i created an issue because i have problems installing it.
sure understand this

**Pull request merged**
